const _globalConstrants = {
    _styles:{
        contentStyle:{
            background: '#fff', padding: 24, margin: 0, minHeight: 720
        },
        styleFLogo:{
            display:"inline-block",
            minWidth:88,
            height:88,
            textAlign:"center",
            verticalAlign:"middle",
            backgroundColor:"#fff",
            border:"1px solid #d9d9d9",
            borderRadius:"4px",
            outline:0,
            cursor:"pointer",
            padding:8,
            margin:8
        },
    },
    _pages:{
        apps:{
            appHR:{
                myInfo:{
                    en:"myInfo",
                    cn:"我的信息",
                },
                officeSupplies:{
                    en:"officeSupplies",
                    cn:"办公用品",
                },
                employeeProfile:{
                    en:"employeeProfile",
                    cn:"员工档案",
                },
                pto:{
                    en:"pto",
                    cn:"请假调休",
                },
                reimbursement:{
                    en:"reimbursement",
                    cn:"报销管理",
                },
                resignationLetter:{
                    en:"resignationLetter",
                    cn:"离职申请",
                },
                announcement:{
                    en:"announcement",
                    cn:"通知公告",
                },
                rulesAndRegulations:{
                    en:"rulesAndRegulations",
                    cn:"规章制度",
                },
                electronicData:{
                    en:"electronicData",
                    cn:"电子资料",
                },
                performanceAppraisal:{
                    en:"performanceAppraisal",
                    cn:"绩效考核",
                },
            },
            appDesignM:{
                design:{
                    en:"design",
                    cn:"品种设计",
                },
                specification:{
                    en:"specification",
                    cn:"设计规范",
                },
                install:{
                    en:"install",
                    cn:"安装规范",
                }
            },
            appMarketM:{
                crm:{
                    en:"crm",
                    cn:"客户信息",
                },
                order:{
                    en:"order",
                    cn:"订单管理",
                },
                approvePrice:{
                    en:"approvePrice",
                    cn:"定价审批",
                },
                approveDeliveryDate:{
                    en:"approveDeliveryDate",
                    cn:"交期审批",
                },
                approvePurchaseRequest:{
                    en:"approvePurchaseRequest",
                    cn:"采购审批",
                },
                approvePrepareGoods:{
                    en:"approvePrepareGoods",
                    cn:"备货审批",
                },
                reconciliation:{
                    en:"reconciliation",
                    cn:"销售对账",
                },
                saleStats:{
                    en:"saleStats",
                    cn:"销售统计",
                },
                returnGoods:{
                    en:"returnGoods",
                    cn:"退货信息",
                }
            },
            appPurchaseM:{
                applyForm:{
                    en:"applyForm",
                    cn:"采购申请",
                },
                inWarehouse:{
                    en:"inWarehouse",
                    cn:"采购入库",
                },
                pay:{
                    en:"pay",
                    cn:"采购付款",
                },
                returnGoods:{
                    en:"returnGoods",
                    cn:"采购退货",
                },
                stats:{
                    en:"stats",
                    cn:"采购统计",
                },
                supplier:{
                    en:"supplier",
                    cn:"供应商",
                },
            },
            appSystemM:{
                passwordReset:{
                    en:"passwordReset",
                    cn:"密码重置",
                },
                authority:{
                    en:"authority",
                    cn:"权限设置",
                },
                information:{
                    en:"information",
                    cn:"信息设置",
                },
                dataArchive:{
                    en:"dataArchive",
                    cn:"数据安全",
                },
                systemSetting:{
                    en:"systemSetting",
                    cn:"系统设置",
                },
            },
            appWarehouseM:{
                productsInOut:{
                    en:"productsInOut",
                    cn:"半/成品",
                },
                rawMaterialInOut:{
                    en:"rawMaterialInOut",
                    cn:"原/材料",
                },
                inventory:{
                    en:"inventory",
                    cn:"库存明细",
                },
                pickRW:{
                    en:"pickRW",
                    cn:"领料记录",
                },
                returnRW:{
                    en:"returnRW",
                    cn:"退料记录",
                },
                packaging:{
                    en:"packaging",
                    cn:"物流管理",
                },
            },
        },
        landingPage:"landing",
        childPages:{
            all:'all',
            viewDetail:'viewDetail',
            createNew:"createNew",
            edit:"edit"
        },
        errorPage:"出错了，未知页面！"
    }
}

export default _globalConstrants;